// Auto-generated API functions for auth
// Do not edit this file manually

import { requestGet, requestPost } from '../index';
import type { ApiResponse, ApiRequestConfig } from '../../types';

/**
 * GetNonce
 * @path GET /auth/nonce
 */
export async function getNonce(params?: { address?: string }): Promise<
  ApiResponse<{
    code: number;
    data: {
      nonce: string;

      /** 2026-01-04T07:43:35.673Z */
      expiresAt: string;
    };
    message: string;
  }>
> {
  return requestGet<{
    code: number;
    data: {
      nonce: string;

      /** 2026-01-04T07:43:35.673Z */
      expiresAt: string;
    };
    message: string;
  }>(`/auth/nonce`, { params });
}

/**
 * AuthLogin
 * @path POST /auth/login
 */
export async function authLogin(
  data: {
    address: string;
    message: string;
    signature: string;
  },
  params?: {
    address?: string;
    message?: string;
    signature?: string;
  }
): Promise<
  ApiResponse<{
    code: number;
    data: {
      token: string;
      tokenType: string;
      expiresAt: string;
      address: string;
    };
    message: string;
  }>
> {
  return requestPost<{
    code: number;
    data: {
      token: string;
      tokenType: string;
      expiresAt: string;
      address: string;
    };
    message: string;
  }>(`/auth/login`, data, { params });
}
