// Auto-generated API functions for contract
// Do not edit this file manually

import { requestGet, requestPost } from '../index';
import type { ApiResponse, ApiRequestConfig } from '../../types';

/**
 * SetContractAddress
 * 存储的用户合约的地址
 * @path POST /contract
 */
export async function setContractAddress(
  data: {
  
  /** 商户钱包地址 */
  address: string;
  
  /** 合约地址 */
  contract: string;
  
  /** nft | membership */
  type: string;
},
  config?: ApiRequestConfig
): Promise<ApiResponse<{
  code: number;
  data: {
  result: boolean;
};
  message: string;
}>> {
  return requestPost<{
  code: number;
  data: {
  result: boolean;
};
  message: string;
}>(`/contract`, data, config);
}
