// Auto-generated API functions for factory
// Do not edit this file manually

import { requestGet, requestPost } from '../index';
import type { ApiResponse, ApiRequestConfig } from '../../types';

/**
 * SetFactoryAddress
 * 获取 存储的用户工厂合约的地址
 * @path POST /factory
 */
export async function setFactoryAddress(
  data: {
  
  /** 商户钱包地址 */
  address: string;
  
  /** 合约地址 */
  factoryAddress: string;
  
  /** nft | membership */
  type: string;
},
  config?: ApiRequestConfig
): Promise<ApiResponse<{
  code: number;
  data: {
  result: boolean;
};
  message: string;
}>> {
  return requestPost<{
  code: number;
  data: {
  result: boolean;
};
  message: string;
}>(`/factory`, data, config);
}
