// Auto-generated API functions for membershipFactory
// Do not edit this file manually

import { requestGet, requestPost } from '../index';
import type { ApiResponse, ApiRequestConfig } from '../../types';

/**
 * SetMembershipFactoryAddress
 * 获取 存储的用户 membership  工厂合约的地址
 * @path POST /membershipFactory
 */
export async function setMembershipFactoryAddress(
  data: {
  
  /** 商户钱包地址 */
  address: string;
  
  /** 合约地址 */
  factoryAddress: string;
},
  config?: ApiRequestConfig
): Promise<ApiResponse<{
  code: number;
  data: {
  result: boolean;
};
  message: string;
}>> {
  return requestPost<{
  code: number;
  data: {
  result: boolean;
};
  message: string;
}>(`/membershipFactory`, data, config);
}
