// Auto-generated API functions for membership
// Do not edit this file manually

import { requestGet, requestPost } from '../index';
import type { ApiResponse, ApiRequestConfig } from '../../types';

/**
 * SetMembershipAddress
 * @path POST /membership/contract
 */
export async function setMembershipAddress(
  data: {
  
  /** 钱包地址 */
  address: string;
  
  /** 合约地址 */
  contractAddress: string;
  
  /** 工厂合约地址 */
  factoryAddress: string;
},
  config?: ApiRequestConfig
): Promise<ApiResponse<unknown>> {
  return requestPost<unknown>(`/membership/contract`, data, config);
}
