// Auto-generated API functions for nft
// Do not edit this file manually

import { requestGet, requestPost } from '../index';
import type { ApiResponse, ApiRequestConfig } from '../../types';

/**
 * SetNftAddress
 * @path POST /nft/contract
 */
export async function setNftAddress(
  data: {
  
  /** 钱包地址 */
  address: string;
  
  /** 子合约地址 */
  contractAddress: string;
  
  /** 工厂合约地址 */
  factoryAddress: string;
},
  config?: ApiRequestConfig
): Promise<ApiResponse<unknown>> {
  return requestPost<unknown>(`/nft/contract`, data, config);
}
