// Auto-generated API functions for oss
// Do not edit this file manually

import { requestGet, requestPost } from '../index';
import type { ApiResponse, ApiRequestConfig } from '../../types';

/**
 * UploadSts
 * @path POST /oss/sts
 */
export async function uploadSts(
  data: {
    address: string;
    contract: string;
    ext: string;
  },
  config?: ApiRequestConfig
): Promise<
  ApiResponse<{
    code: number;
    data: {
      sts: {
        accessKeyId: string; // "STS.NZ3jreLQ5hXjrPD95sUbgqcUh",
        accessKeySecret: string; // "7mBX2NgKxEkkzx2tKhbZHCXGBF6pLq4yVnrwwB3pdiUa",
        securityToken: string;
        expiration: string; // "2026-01-04T13:16:19Z"
      };
      region: string; // 'oss-cn-hongkong';
      objectKey: string; // 'ddcsource/contracts/44508/0x1f7a9d34768e052b57783dc2ac2e7ff5125080bd/assets/3dfdd219a066e6e73365ba03c5803eef.png';
      objectUrlHint: string; // 'https://source.datadance.ai/contracts/44508/0x1f7a9d34768e052b57783dc2ac2e7ff5125080bd/assets/3dfdd219a066e6e73365ba03c5803eef.png';
      type: string; // 'image';
      fileId: string; // '3dfdd219a066e6e73365ba03c5803eef';
      callback: {
        url: string; // 'http://8.210.164.150/api/v1/oss/callback';
        contentType: string; // 'application/x-www-form-urlencoded';
        body: string; // 'bucket=${bucket}&ossKey=${object}&etag=${etag}&size=${size}&mimeType=${mimeType}&fileId=3dfdd219a066e6e73365ba03c5803eef';
      };
    };
    message: string;
  }>
> {
  return requestPost<{
    code: number;
    data: {
      sts: {
        accessKeyId: string;
        accessKeySecret: string;
        securityToken: string;
        expiration: string;
      };
      region: string;
      objectKey: string;
      objectUrlHint: string;
      type: string;
      fileId: string;
      callback: {
        url: string;
        contentType: string;
        body: string;
      };
    };
    message: string;
  }>(`/oss/sts`, data, config);
}
