// Auto-generated API functions for transfer
// Do not edit this file manually

import { requestGet, requestPost } from '../index';
import type { ApiResponse, ApiRequestConfig } from '../../types';

/**
 * TransferContractOwner
 * 存储的用户合约的地址
 * @path POST /transfer
 */
export async function transferContractOwner(
  data: {
  
  /** 商户钱包地址 */
  address: string;
  
  /** 合约地址 */
  contract: string;
  
  /** nft | membership */
  type: string;
  
  /** 转移的新owner 钱包地址 */
  ownerAddress: string;
},
  config?: ApiRequestConfig
): Promise<ApiResponse<{
  code: number;
  data: {
  result: boolean;
};
  message: string;
}>> {
  return requestPost<{
  code: number;
  data: {
  result: boolean;
};
  message: string;
}>(`/transfer`, data, config);
}
